// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using UrlCompressorService.Models;

namespace UrlCompressorService.Migrations
{
    [DbContext(typeof(UrlEntryContext))]
    [Migration("20171010181649_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("UrlCompressorService.Models.UrlEntry", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreationDate");

                    b.Property<string>("Guid");

                    b.Property<string>("LongUrl")
                        .IsRequired();

                    b.Property<int>("RedirectCount");

                    b.Property<string>("ShortUrl");

                    b.HasKey("ID");

                    b.ToTable("UrlEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
